language: python

addons:
  postgresql: "9.3"
  
before_script:
  - psql -c 'create database test;' -U postgres
  - psql -U postgres -c "create extension postgis"


install:
    - pip install psycopg2 coverage coveralls
    - pip install -e .
    
script:
    - coverage run runtests.py
    
after_success: coveralls
